# This is a basic workflow to help you get started with Actions

name: Teste Cypress

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
    # Setup do Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version}}
      
      # Instalando dependencias
      - run: npm install
      
      # Executar os testes usando cucumber
      
      - run: npm run cy:run
      
      # Realiza o merged dos arquivos .json de cada spec
      - run: npm run report:merge
      
      # Gera o relatorio em HTML
      - run: npm run report:mocha
      
      # Limpa os arquivos gerados para criação do relátorio
      
      - run: npm run report:clean
      
      # Publicar relatorio  html utilizando git hub pages
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
           token: ${{ github.token }}
           branch: gh-pages
           FOLDER: mochawesome-report
